name: Setup Dependencies
description: Installs Yarn 3 and dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'
        cache: 'yarn'

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install Yarn 3
      run: yarn set version 3.3.1
      shell: bash

    - name: Get yarn cache directory path
      id: yarn-cache-dir
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: steps.yarn-cache-dir.outputs.dir
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --no-immutable
      shell: bash
